name: run-training-file-on-commit
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pist
          if [ -f requirements.txt ]; then pip install -r requirements.txt;   

      - name: Execute Training script # Run the specified file from the repo
        run: python train.py
